// The app icon and splash images are generated by scripts/make-brand-assets.mjs.
// This guards against a missing, resized or template-default file sneaking back in:
// a wrong-sized icon is rejected by the stores and an Expo template icon looks unfinished.

import { readFileSync } from "node:fs";
import { join } from "node:path";

const assets = join(__dirname, "..", "..", "assets");

// A PNG's width and height are stored at fixed offsets in its first chunk.
function pngSize(file: string): { width: number; height: number } {
  const buf = readFileSync(join(assets, file));
  expect(buf.subarray(1, 4).toString("ascii")).toBe("PNG");
  return { width: buf.readUInt32BE(16), height: buf.readUInt32BE(20) };
}

describe("brand assets", () => {
  it.each(["icon.png", "android-icon-foreground.png", "android-icon-background.png", "android-icon-monochrome.png", "splash-icon.png"])(
    "%s is 1024 x 1024",
    (file) => {
      expect(pngSize(file)).toEqual({ width: 1024, height: 1024 });
    },
  );

  it("favicon is a small square", () => {
    const { width, height } = pngSize("favicon.png");
    expect(width).toBe(height);
    expect(width).toBeLessThanOrEqual(64);
  });

  it("the icon is Fieldnote's own, not the Expo template's", () => {
    // The template icon was a 393,493-byte blue chevron on a blueprint grid.
    const bytes = readFileSync(join(assets, "icon.png")).length;
    expect(bytes).not.toBe(393493);
  });
});
