// metro.config.js
//
// Metro is the bundler that packages every file into the app. By default it
// only knows how to bundle JS/TS/JSON/assets — it has no idea what a `.sql`
// file is. `drizzle/migrations.js` (generated by drizzle-kit) imports our
// migration files directly:
//
//   import m0000 from './0000_init.sql';
//
// This one line tells Metro to treat `.sql` as a source file it can import,
// which is what makes that line work instead of crashing the bundler.
// Source: https://orm.drizzle.team/docs/get-started/expo-new — check that
// page if this stops working after a Metro/Expo upgrade (Section 3.4.3
// warns this integration changes often).

const { getDefaultConfig } = require("expo/metro-config");

const config = getDefaultConfig(__dirname);

config.resolver.sourceExts.push("sql");

// --- Web-only: let expo-sqlite's browser backend actually run ---------------
//
// This app's real targets are Android and iOS, which use native on-device
// SQLite and need none of this. `npm run web` is dev-tooling only — a way to
// preview screens without an emulator — but expo-sqlite still tries to open
// a database when the app boots, on every platform, web included. Without
// this, that attempt fails immediately with
// `ReferenceError: SharedArrayBuffer is not defined` — see
// scripts/dev-web-coi-proxy.js for the rest of this fix (the response
// headers this needs can't be set from here — see that file's comment).
config.resolver.assetExts.push("wasm");

module.exports = config;
