// metro.config.js
//
// Metro is the bundler that packages every file into the app. By default it
// only knows how to bundle JS/TS/JSON/assets — it has no idea what a `.sql`
// file is. `drizzle/migrations.js` (generated by drizzle-kit) imports our
// migration files directly:
//
//   import m0000 from './0000_init.sql';
//
// This one line tells Metro to treat `.sql` as a source file it can import,
// which is what makes that line work instead of crashing the bundler.
// Source: https://orm.drizzle.team/docs/get-started/expo-new — check that
// page if this stops working after a Metro/Expo upgrade (Section 3.4.3
// warns this integration changes often).

const { getDefaultConfig } = require("expo/metro-config");

const config = getDefaultConfig(__dirname);

config.resolver.sourceExts.push("sql");

module.exports = config;
